const data ={
    products:[
        {
            _id:'1',
            name:'LFM Black Hood SE - Classic Style',
            category:'Coat',
            image:'/images/product-1.png',
            price:129.90,
            brand:'LAFAMIGLIA',
            rating:5,
            numReviews:10,
            description:'High Quality Product',
        },
        {
            _id:'2',
            name:'LFM Black Hood - Minimalist Style',
            category:'Coat',
            image:'/images/product-2.png',
            price:119.90,
            brand:'LAFAMIGLIA',
            rating:4.5,
            numReviews:5,
            description:'High Quality Product',
        },
        {
            _id:'3',
            name:'LFM Grey Hood - Minimalist Style',
            category:'Coat',
            image:'/images/product-3.png',
            price:119.90,
            brand:'LAFAMIGLIA',
            rating:5,
            numReviews:7,
            description:'High Quality Product',
        },
        {
            _id:'4',
            name:'LFM Grey Hood SE - Classic Style',
            category:'Coat',
            image:'/images/product-4.png',
            price:129.90,
            brand:'LAFAMIGLIA',
            rating:5,
            numReviews:10,
            description:'High Quality Product',
        },
        {
            _id:'5',
            name:'LFM T-Shirt - Minimalist Style',
            category:'shirt',
            image:'/images/product-5.png',
            price:29.90,
            brand:'LAFAMIGLIA',
            rating:4.4,
            numReviews:14,
            description:'High Quality Product',
        },
        {
            _id:'6',
            name:'LFM Grey Shorts - Minimalist Style',
            category:'Shorts',
            image:'/images/product-6.png',
            price:49.90,
            brand:'LAFAMIGLIA',
            rating:4.6,
            numReviews:6,
            description:'High Quality Product',
        },
        {
            _id:'7',
            name:'LFM Black Shorts - Minimalist Style',
            category:'Shorts',
            image:'/images/product-7.png',
            price:49.90,
            brand:'LAFAMIGLIA',
            rating:5,
            numReviews:10,
            description:'High Quality Product',
        }
    ]
}
export default data